# Alembic configuration file

[alembic]
# path to migration scripts
sqlalchemy.url = driver://user:password@localhost/dbname
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be named with dates
# file_template = %%(rev)s-%%(epoch)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to the constructor of datetime.datetime
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field:
# set to 0 to disable the slashing of the slug field.
# Note that the reconciliation algorithm used to determine new and deleted
# files uses this length to determine whether two files are "the same"
# as far as it is concerned, so you should not change this after running
# first migrations.
truncate_slug_length = 40

# set multiple here if you want to track multiple version tables
# version_table_schema = myapp

# Template used to generate migration script names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below to set an epoch-based migration naming scheme template
#file_template = %%(epoch)s_%%(rev)s_%%(slug)s

[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
